package Interfaz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */


import espacios.AdministradorEspacios;
import espacios.Espacio;
import espacios.TipoEspacio;
import excepciones.EspacioAlquiladoException;
import excepciones.EspacioDuplicadoException;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yumor
 */
public class FrmEspacio extends javax.swing.JInternalFrame {

    private  AdministradorEspacios controlador;
    
    /**
     * Creates new form FrmEspacio
     */
     public FrmEspacio(AdministradorEspacios controlador) {
        initComponents();
        this.controlador = controlador;
        cargarTabla();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDatos = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        jNumero = new javax.swing.JLabel();
        jTipo = new javax.swing.JLabel();
        jPrecioMensual = new javax.swing.JLabel();
        jDisponible = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jcTipo = new javax.swing.JComboBox<>();
        jcCapacidad = new javax.swing.JComboBox<>();
        jCapacidad = new javax.swing.JLabel();
        txtPrecioMensual = new javax.swing.JTextField();
        jCheckDisponible = new javax.swing.JCheckBox();
        jpBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEspaciosLista = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jpDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTitulo.setBackground(new java.awt.Color(24, 95, 165));
        jTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setText("Datos del Espacio");
        jTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTitulo.setOpaque(true);

        jNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNumero.setForeground(new java.awt.Color(0, 0, 0));
        jNumero.setText("Numero:");

        jTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTipo.setForeground(new java.awt.Color(0, 0, 0));
        jTipo.setText("Tipo:");

        jPrecioMensual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPrecioMensual.setForeground(new java.awt.Color(0, 0, 0));
        jPrecioMensual.setText("Precio Mensual:");

        jDisponible.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDisponible.setText("Disponible ");

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande", " " }));
        jcTipo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jcTipoComponentHidden(evt);
            }
        });
        jcTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTipoActionPerformed(evt);
            }
        });

        jcCapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "20", " " }));

        jCapacidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCapacidad.setForeground(new java.awt.Color(0, 0, 0));
        jCapacidad.setText("Capacidad");

        jCheckDisponible.setText("Disponible");
        jCheckDisponible.setEnabled(false);

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPrecioMensual)
                            .addComponent(jCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDisponible))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckDisponible)
                            .addComponent(jcCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(146, Short.MAX_VALUE))
            .addComponent(jTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPrecioMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrecioMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(428, 428, 428)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckDisponible))
                .addContainerGap())
        );

        jpBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGuardar.setBackground(new java.awt.Color(24, 95, 165));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setOpaque(true);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(15, 110, 86));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(121, 31, 31));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setOpaque(true);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(95, 94, 90));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setOpaque(true);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblEspaciosLista.setAutoCreateRowSorter(true);
        tblEspaciosLista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblEspaciosLista.setForeground(new java.awt.Color(12, 68, 124));
        tblEspaciosLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero", "Tipo", "Capacidad", "Precio Mensual ", "Disponible "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEspaciosLista.setRowHeight(28);
        tblEspaciosLista.setSelectionBackground(new java.awt.Color(181, 212, 244));
        tblEspaciosLista.setShowGrid(true);
        jScrollPane1.setViewportView(tblEspaciosLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcTipoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jcTipoComponentHidden

    }//GEN-LAST:event_jcTipoComponentHidden

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
     try {
        int numero = Integer.parseInt(txtNumero.getText().trim());
          TipoEspacio tipo = obtenerTipoSeleccionado();
          if (tipo == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un tipo de espacio válido.");
            return;
        }
         Espacio nuevo = new Espacio(numero, tipo);
         controlador.agregar(nuevo);
         JOptionPane.showMessageDialog(this, "Espacio " + numero + " agregado correctamente.");
         cargarTabla();
         limpiarCampos();
} catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El número debe ser un valor entero.");
} catch (EspacioDuplicadoException ex) {
        JOptionPane.showMessageDialog(this,"Ya existe un espacio con ese número.");
}
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       try {
            int numero = Integer.parseInt(txtNumero.getText().trim());
            TipoEspacio tipo = obtenerTipoSeleccionado();
            if (tipo == null) {
                JOptionPane.showMessageDialog(this, "Seleccione un tipo de espacio válido.");
                return;
            }
            double precioMensual = Double.parseDouble(txtPrecioMensual.getText().trim());

            boolean actualizado = controlador.actualizar(numero, tipo, precioMensual);
            if (actualizado) {
                JOptionPane.showMessageDialog(this, "Espacio " + numero + " actualizado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el espacio " + numero + ".");
            }
            cargarTabla();
            limpiarCampos();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Verifique que número y precio sean valores numéricos.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      try {
            int numero = Integer.parseInt(txtNumero.getText().trim());
            boolean eliminado = controlador.eliminar(numero);
            if (eliminado) {
                JOptionPane.showMessageDialog(this, "Espacio " + numero + " eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el espacio " + numero + ".");
            }
            cargarTabla();
            limpiarCampos();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El número debe ser un valor entero.");
        } catch (EspacioAlquiladoException ex) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar: el espacio está ocupado.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         FrmFiltradoBuscar frmBuscar = new FrmFiltradoBuscar(controlador, this);
         getDesktopPane().add(frmBuscar);
         frmBuscar.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jcTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTipoActionPerformed
       asignarDatosPorTipo();
    }//GEN-LAST:event_jcTipoActionPerformed

    private void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblEspaciosLista.getModel();
        modelo.setRowCount(0);
        for (Espacio espacio : controlador.getEspacios()) {
            modelo.addRow(new Object[]{
                espacio.getNumero(),
                tipoATexto(espacio.getTipo()),
                espacio.getCapacidad(),
                espacio.getPrecioMensual(),
                espacio.isDisponible()
            });
        }
    }

    public void mostrarEspacio(Espacio espacio) {
        txtNumero.setText(String.valueOf(espacio.getNumero()));
        jcTipo.setSelectedItem(tipoATexto(espacio.getTipo()));
        jcCapacidad.setSelectedItem(String.valueOf((int) espacio.getCapacidad()));
        txtPrecioMensual.setText(String.valueOf(espacio.getPrecioMensual()));
        jCheckDisponible.setSelected(espacio.isDisponible());
    }
    
    private void limpiarCampos() {
        txtNumero.setText("");
        jcTipo.setSelectedIndex(jcTipo.getItemCount()-1);
        jcCapacidad.setSelectedIndex(jcCapacidad.getItemCount()-1);
        txtPrecioMensual.setText("");
        jCheckDisponible.setSelected(false);
    }
    
      private void asignarDatosPorTipo() {
        TipoEspacio tipo = obtenerTipoSeleccionado();
        if (tipo == null) {
            return;
        }
        Espacio temporal = new Espacio(0, tipo);
        jcCapacidad.setSelectedItem(String.valueOf((int) temporal.getCapacidad()));
        txtPrecioMensual.setText(String.valueOf(temporal.getPrecioMensual()));
    }
      
     private TipoEspacio obtenerTipoSeleccionado() {
        String seleccion = (String) jcTipo.getSelectedItem();
        if (seleccion == null) {
            return null;
        }
        switch (seleccion) {
            case "Pequeño":
                return TipoEspacio.PEQUEÑO;
            case "Mediano":
                return TipoEspacio.MEDIANO;
            case "Grande":
                return TipoEspacio.GRANDE;
            default:
                return null;
        }
    }
 
    private String tipoATexto(TipoEspacio tipo) {
        if (tipo == null) {
            return " ";
        }
        switch (tipo) {
            case PEQUEÑO:
                return "Pequeño";
            case MEDIANO:
                return "Mediano";
            case GRANDE:
                return "Grande";
            default:
                return " ";
        }
    }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jCapacidad;
    private javax.swing.JCheckBox jCheckDisponible;
    private javax.swing.JLabel jDisponible;
    private javax.swing.JLabel jNumero;
    private javax.swing.JLabel jPrecioMensual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTipo;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JComboBox<String> jcCapacidad;
    private javax.swing.JComboBox<String> jcTipo;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JTable tblEspaciosLista;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecioMensual;
    // End of variables declaration//GEN-END:variables
}
