/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import clientes.Cliente;
import clientes.ControladorCliente;
import espacios.FrmEspacio;
import espacios.FrmFiltradoBuscar;
import Interfaz.JInFrmServicio;
import servicios.Controladorservicio;

/**
 *
 * @author bryan
 */
public class FrmStorageBox extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmStorageBox.class.getName());
    private ControladorCliente controladorCliente = new ControladorCliente();
    private espacios.AdministradorEspacios administradorEspacios = new espacios.AdministradorEspacios();
    private FrmFiltradoBuscar frmBuscarEspacio;
    private servicios.Controladorservicio controladorservicio = new servicios.Controladorservicio();
    private JInlFrmBuscarServicio frmBuscarServicio;

    /**
     * Creates new form FrmStorageBox
     */
    public FrmStorageBox() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        MenuServicio = new javax.swing.JMenu();
        itmServicio = new javax.swing.JMenuItem();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCliente = new javax.swing.JMenu();
        itmCliente = new javax.swing.JMenuItem();
        itmBuscarCliente = new javax.swing.JMenuItem();
        MenuEspacio = new javax.swing.JMenu();
        itmEspacio = new javax.swing.JMenuItem();
        itmBuscarEspacio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        MenuServicio = new javax.swing.JMenu();
        itmServicio = new javax.swing.JMenuItem();
        itmBuscarServicio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jMenuBar1.setMinimumSize(new java.awt.Dimension(70, 70));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 70));

        MenuCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 50, 8, 50));
        MenuCliente.setText("Cliente");
        MenuCliente.setMargin(new java.awt.Insets(8, 20, 8, 20));
        MenuCliente.addActionListener(this::MenuClienteActionPerformed);

        itmCliente.setText("Cliente");
        itmCliente.addActionListener(this::itmClienteActionPerformed);
        MenuCliente.add(itmCliente);

        itmBuscarCliente.setText("Buscar cliente");
        itmBuscarCliente.addActionListener(this::itmBuscarClienteActionPerformed);
        MenuCliente.add(itmBuscarCliente);

        jMenuBar1.add(MenuCliente);

        MenuEspacio.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 50, 8, 50));
        MenuEspacio.setText("Espacio");

        itmEspacio.setText("Espacio");
        itmEspacio.addActionListener(this::itmEspacioActionPerformed);
        MenuEspacio.add(itmEspacio);

        itmBuscarEspacio.setText("BuscarEspacio");
        itmBuscarEspacio.addActionListener(this::itmBuscarEspacioActionPerformed);
        MenuEspacio.add(itmBuscarEspacio);

        jMenuBar1.add(MenuEspacio);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");
        jMenuBar1.add(jMenu4);

        MenuServicio.setText("Servicio");

        itmServicio.setText("servicios");
        itmServicio.addActionListener(this::itmServicioActionPerformed);
        MenuServicio.add(itmServicio);

        itmBuscarServicio.setText("Buscar servicio");
        itmBuscarServicio.addActionListener(this::itmBuscarServicioActionPerformed);
        MenuServicio.add(itmBuscarServicio);

        jMenuBar1.add(MenuServicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClienteActionPerformed

    }//GEN-LAST:event_MenuClienteActionPerformed

    private void itmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmClienteActionPerformed
        FrmCliente ventanaCliente = new FrmCliente(controladorCliente);
        jDesktopPane1.add(ventanaCliente);
        ventanaCliente.setVisible(true);
        try {
            ventanaCliente.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }//GEN-LAST:event_itmClienteActionPerformed

    private void itmBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarClienteActionPerformed
        FrmBuscarCliente frm = new FrmBuscarCliente(controladorCliente);
        jDesktopPane1.add(frm);
        frm.setVisible(true);
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }//GEN-LAST:event_itmBuscarClienteActionPerformed

    private void itmEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEspacioActionPerformed
        FrmEspacio ventanaEspacio = new FrmEspacio(administradorEspacios);
        jDesktopPane1.add(ventanaEspacio);
        ventanaEspacio.setVisible(true);
        try {
            ventanaEspacio.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }


    }//GEN-LAST:event_itmEspacioActionPerformed

    private void itmBuscarEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarEspacioActionPerformed
        if (frmBuscarEspacio != null && !frmBuscarEspacio.isClosed()) {
            try {
                frmBuscarEspacio.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
            }
            return;
        }

        frmBuscarEspacio = new FrmFiltradoBuscar(administradorEspacios);
        jDesktopPane1.add(frmBuscarEspacio);
        frmBuscarEspacio.setVisible(true);
        try {
            frmBuscarEspacio.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }

    }//GEN-LAST:event_itmBuscarEspacioActionPerformed

    private void itmServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmServicioActionPerformed
        JInFrmServicio frm = new JInFrmServicio(controladorservicio);

        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_itmServicioActionPerformed

    private void itmBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarServicioActionPerformed
        if (frmBuscarServicio != null && !frmBuscarServicio.isClosed()) {
            try {
                frmBuscarServicio.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
            }
            return;
        }

        frmBuscarServicio
                = new JInlFrmBuscarServicio(controladorservicio);

        jDesktopPane1.add(frmBuscarServicio);

        frmBuscarServicio.setVisible(true);

        try {
            frmBuscarServicio.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }//GEN-LAST:event_itmBuscarServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmStorageBox().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JMenu MenuEspacio;
    private javax.swing.JMenu MenuServicio;
    private javax.swing.JMenuItem itmBuscarCliente;
    private javax.swing.JMenuItem itmBuscarEspacio;
    private javax.swing.JMenuItem itmBuscarServicio;
    private javax.swing.JMenuItem itmCliente;
    private javax.swing.JMenuItem itmEspacio;
    private javax.swing.JMenuItem itmServicio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
